# HS NBA existing customer model configuration
model_id: 7001

target_column: 'model_scenario'

target: 'target'

customer_id_fields:
    - cust_id
    - ban
    - lpds_id

customer_ids:
    - name: cust_id
      type: int
    - name: cust_src_id
      type: int
    - name: ban
      type: int
    - name: ban_src_id
      type: int
    - name: lpds_id
      type: int
    - name: fms_address_id
      type: int
      
target_variables:
    acquisition:
    - name: hsic_acquisition
      class_index: 0
    - name: ttv_acquisition
      class_index: 1
    - name: shs_acquisition
      class_index: 2
    - name: sing_acquisition
      class_index: 3
    - name: tos_acquisition
      class_index: 4
    - name: lwc_acquisition
      class_index: 5
    - name: sws_acquisition
      class_index: 6
    - name: wifi_acquisition
      class_index: 7
    - name: whsia_acquisition
      class_index: 8
    - name: hpro_acquisition
      class_index: 9
    tier:
    - name: hsic_low_tier_acquisition
      class_index: 0
    - name: hsic_medium_tier_acquisition
      class_index: 1
    - name: hsic_high_tier_acquisition
      class_index: 2
    - name: tos_basic_tier_acquisition
      class_index: 3
    - name: tos_standard_tier_acquisition
      class_index: 4
    - name: tos_ultimate_tier_acquisition
      class_index: 5
    - name: tos_complete_tier_acquisition
      class_index: 6

features:
    - name: avg_usg_cnt_4w_news 
      type: float64
    - name: avg_usg_dl_4w_news 
      type: float64
    - name: avg_usg_ul_4w_news 
      type: float64
    - name: avg_usg_cnt_4w_sports 
      type: float64
    - name: avg_usg_dl_4w_sports 
      type: float64
    - name: avg_usg_ul_4w_sports 
      type: float64
    - name: avg_usg_cnt_4w_tv_and_movies 
      type: float64
    - name: avg_usg_dl_4w_tv_and_movies 
      type: float64
    - name: avg_usg_ul_4w_tv_and_movies 
      type: float64
    - name: avg_usg_cnt_4w_gaming 
      type: float64
    - name: avg_usg_dl_4w_gaming 
      type: float64
    - name: avg_usg_ul_4w_gaming 
      type: float64
    - name: avg_usg_cnt_4w_smarthome_automation 
      type: float64
    - name: avg_usg_dl_4w_smarthome_automation 
      type: float64
    - name: avg_usg_ul_4w_smarthome_automation 
      type: float64
    - name: avg_usg_cnt_4w_smarthome_security 
      type: float64
    - name: avg_usg_dl_4w_smarthome_security 
      type: float64
    - name: avg_usg_ul_4w_smarthome_security 
      type: float64
    - name: avg_usg_cnt_4w_shopping_deals 
      type: float64
    - name: avg_usg_dl_4w_shopping_deals 
      type: float64
    - name: avg_usg_ul_4w_shopping_deals 
      type: float64
    - name: avg_usg_cnt_4w_telus 
      type: float64
    - name: avg_usg_dl_4w_telus 
      type: float64
    - name: avg_usg_ul_4w_telus 
      type: float64
    - name: bill_wls_avg_zscore_ban_subtotal_amt 
      type: float64
    - name: bill_wls_avg_ban_subtotal_amt 
      type: float64
    - name: bill_wls_stddev_ban_subtotal_amt 
      type: float64
    - name: bill_wls_avg_zscore_ban_debit_amt 
      type: float64
    - name: bill_wls_avg_ban_debit_amt 
      type: float64
    - name: bill_wls_stddev_ban_debit_amt 
      type: float64
    - name: bill_wls_avg_zscore_ban_discount_amt 
      type: float64
    - name: bill_wls_avg_ban_discount_amt 
      type: float64
    - name: bill_wls_stddev_ban_discount_amt 
      type: float64
    - name: bill_wls_avg_zscore_ban_credit_amt 
      type: float64
    - name: bill_wls_avg_ban_credit_amt 
      type: float64
    - name: bill_wls_stddev_ban_credit_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_mthly_debit_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_mthly_discount_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_mthly_credit_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_addon_debit_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_addon_discount_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_addon_credit_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_other_debit_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_other_discount_amt 
      type: float64
    - name: bill_wls_avg_zscore_rc_other_credit_amt 
      type: float64
    - name: bill_wls_avg_zscore_oc_device_debit_amt 
      type: float64
    - name: bill_wls_avg_zscore_oc_device_discount_amt 
      type: float64
    - name: bill_wls_avg_zscore_oc_device_credit_amt 
      type: float64
    - name: bill_wls_avg_zscore_msg_cnt 
      type: float64
    - name: bill_wls_avg_zscore_roam_day_cnt 
      type: float64
    - name: bill_wls_avg_zscore_data_usg_gb 
      type: float64
    - name: bill_wls_avg_zscore_call_usage_min 
      type: float64
    - name: bill_wls_avg_rc_debit_amt 
      type: float64
    - name: bill_wls_avg_rc_discount_amt 
      type: float64
    - name: bill_wls_avg_rc_credit_amt 
      type: float64
    - name: bill_wls_avg_rc_addon_debit_amt 
      type: float64
    - name: bill_wls_avg_rc_addon_discount_amt 
      type: float64
    - name: bill_wls_avg_rc_addon_credit_amt 
      type: float64
    - name: bill_wls_avg_rc_other_debit_amt 
      type: float64
    - name: bill_wls_avg_rc_other_discount_amt 
      type: float64
    - name: bill_wls_avg_rc_other_credit_amt 
      type: float64
    - name: bill_wls_avg_device_debit_amt 
      type: float64
    - name: bill_wls_avg_device_discount_amt 
      type: float64
    - name: bill_wls_avg_device_credit_amt 
      type: float64
    - name: bill_wls_avg_msg_cnt 
      type: float64
    - name: bill_wls_avg_roam_day_cnt 
      type: float64
    - name: bill_wls_avg_data_usg_gb 
      type: float64
    - name: bill_wls_avg_call_usg_min 
      type: float64
    - name: bill_wls_stddev_rc_debit_amt 
      type: float64
    - name: bill_wls_stddev_rc_discount_amt 
      type: float64
    - name: bill_wls_stddev_rc_credit_amt 
      type: float64
    - name: bill_wls_stddev_rc_addon_debit_amt 
      type: float64
    - name: bill_wls_stddev_rc_addon_discount_amt 
      type: float64
    - name: bill_wls_stddev_rc_addon_credit_amt 
      type: float64
    - name: bill_wls_stddev_rc_other_debit_amt 
      type: float64
    - name: bill_wls_stddev_rc_other_discount_amt 
      type: float64
    - name: bill_wls_stddev_rc_other_credit_amt 
      type: float64
    - name: bill_wls_stddev_device_debit_amt 
      type: float64
    - name: bill_wls_stddev_device_discount_amt 
      type: float64
    - name: bill_wls_stddev_device_credit_amt 
      type: float64
    - name: bill_wls_stddev_msg_cnt 
      type: float64
    - name: bill_wls_stddev_roam_day_cnt 
      type: float64
    - name: bill_wls_stddev_data_usg_gb 
      type: float64
    - name: bill_wls_stddev_call_usg_min 
      type: float64
    - name: bill_wls_tot_disc_pct 
      type: float64
    - name: bill_wls_rc_disc_pct 
      type: float64
    - name: bill_wls_rc_addon_disc_pct 
      type: float64
    - name: bill_wls_rc_other_disc_pct 
      type: float64
    - name: bill_wls_device_disc_pct 
      type: float64
    - name: call_cnt 
      type: int
    - name: call_avg_talk_time 
      type: float64
    - name: call_avg_hold_time 
      type: float64
    - name: call_avg_emp_cnt 
      type: float64
    - name: call_avg_esc_cnt 
      type: float64
    - name: call_std_talk_time 
      type: float64
    - name: call_std_hold_time 
      type: float64
    - name: call_std_emp_cnt 
      type: float64
    - name: call_std_esc_cnt 
      type: float64
    - name: call_sum_talk_time 
      type: float64
    - name: call_sum_hold_time 
      type: float64
    - name: call_sum_emp_cnt 
      type: int
    - name: call_sum_esc_cnt 
      type: int
    - name: call_max_talk_time 
      type: float64
    - name: call_max_hold_time 
      type: float64
    - name: call_max_emp_cnt 
      type: int
    - name: call_max_esc_cnt 
      type: int
    - name: clk_wls_tot_cnt_r30d 
      type: int
    - name: clk_wls_plan_cnt_r30d 
      type: int
    - name: clk_wls_device_cnt_r30d 
      type: int
    - name: clk_wls_smartwatch_cnt_r30d 
      type: int
    - name: clk_wls_tablet_cnt_r30d 
      type: int
    - name: clk_wln_tot_cnt_r30d 
      type: int
    - name: clk_wln_eligibility_cnt_r30d 
      type: int
    - name: clk_wln_sing_cnt_r30d 
      type: int
    - name: clk_wln_hsic_cnt_r30d 
      type: int
    - name: clk_wln_fibre_cnt_r30d 
      type: int
    - name: clk_wln_whsia_cnt_r30d 
      type: int
    - name: clk_wln_wifi_plus_cnt_r30d 
      type: int
    - name: clk_wln_tv_cnt_r30d 
      type: int
    - name: clk_wln_optik_cnt_r30d 
      type: int
    - name: clk_wln_pik_cnt_r30d 
      type: int
    - name: clk_wln_streamplus_cnt_r30d 
      type: int
    - name: clk_wln_streaming_cnt_r30d 
      type: int
    - name: clk_wln_security_cnt_r30d 
      type: int
    - name: clk_wln_smarthome_security_cnt_r30d 
      type: int
    - name: clk_wln_online_security_cnt_r30d 
      type: int
    - name: clk_wln_smartwear_security_cnt_r30d 
      type: int
    - name: clk_deal_tot_cnt_r30d 
      type: int
    - name: clk_deal_wls_cnt_r30d 
      type: int
    - name: clk_deal_wln_cnt_r30d 
      type: int
    - name: clk_deal_wln_sing_cnt_r30d 
      type: int
    - name: clk_deal_wln_hsic_cnt_r30d 
      type: int
    - name: clk_deal_wln_whsia_cnt_r30d 
      type: int
    - name: clk_deal_wln_tv_cnt_r30d 
      type: int
    - name: clk_deal_wln_security_cnt_r30d 
      type: int
    - name: clk_upgr_tot_cnt_r30d 
      type: int
    - name: clk_upgr_wls_cnt_r30d 
      type: int
    - name: clk_upgr_wln_cnt_r30d 
      type: int
    - name: clk_upgr_wln_sing_cnt_r30d 
      type: int
    - name: clk_upgr_wln_hsic_cnt_r30d 
      type: int
    - name: clk_upgr_wln_whsia_cnt_r30d 
      type: int
    - name: clk_upgr_wln_tv_cnt_r30d 
      type: int
    - name: clk_upgr_wln_security_cnt_r30d 
      type: int
    - name: clk_chg_tot_cnt_r30d 
      type: int
    - name: clk_chg_wls_cnt_r30d 
      type: int
    - name: clk_chg_wln_cnt_r30d 
      type: int
    - name: clk_chg_wln_sing_cnt_r30d 
      type: int
    - name: clk_chg_wln_hsic_cnt_r30d 
      type: int
    - name: clk_chg_wln_whsia_cnt_r30d 
      type: int
    - name: clk_chg_wln_tv_cnt_r30d 
      type: int
    - name: clk_chg_wln_security_cnt_r30d 
      type: int
    - name: clk_health_livingwell_cnt_r30d 
      type: int
    - name: clk_health_mypet_cnt_r30d 
      type: int
    - name: clk_travel_cnt_r30d 
      type: int
    - name: clk_billing_cnt_r30d 
      type: int
    - name: clk_service_agreement_cnt_r30d 
      type: int
    - name: telus_corp_stores_per_csd 
      type: int
    - name: fsa_crime_ind 
      type: int
    - name: demogr_med_age 
      type: float64
    - name: demogr_avg_child 
      type: float64
    - name: demogr_pct_family_with_child_living_at_home 
      type: float64
    - name: demogr_employment_rate 
      type: float64
    - name: demogr_avg_household_size 
      type: float64
    - name: demogr_avg_income 
      type: float64
    - name: demogr_med_income 
      type: float64
    - name: demogr_urban_flag 
      type: float64
    - name: demogr_rural_flag 
      type: float64
    - name: demogr_family_flag 
      type: float64
    - name: demogr_lsname_large_diverse_families 
      type: float64
    - name: demogr_lsname_younger_singles_and_couples 
      type: float64
    - name: demogr_lsname_very_young_singles_and_couples 
      type: float64
    - name: demogr_lsname_older_families_and_empty_nests 
      type: float64
    - name: demogr_lsname_middle_age_families 
      type: float64
    - name: demogr_lsname_mature_singles_and_couples 
      type: float64
    - name: demogr_lsname_young_families 
      type: float64
    - name: demogr_lsname_school_age_families 
      type: float64
    - name: demogr_retired_pstl_cd_ind 
      type: float64
    - name: demogr_census_division_typ 
      type: string
    - name: demogr_lifestage_sort 
      type: float64
    - name: apple_ind 
      type: int
    - name: google_ind 
      type: int
    - name: samsung_ind 
      type: int
    - name: dvc_age_day 
      type: int
    - name: is_5g_capable 
      type: string
    - name: is_4g_capable 
      type: string
    - name: grey_mrkt_ind 
      type: int
    - name: dvc_typ 
      type: string
    - name: chatr_mobile_market_share 
      type: float64
    - name: cityfone_market_share 
      type: float64
    - name: fido_market_share 
      type: float64
    - name: freedom_mobile_market_share 
      type: float64
    - name: koodo_mobile_market_share 
      type: float64
    - name: lucky_mobile_market_share 
      type: float64
    - name: pc_mobile_market_share 
      type: float64
    - name: public_mobile_market_share 
      type: float64
    - name: rogers_market_share 
      type: float64
    - name: sask_tel_mobility_market_share 
      type: float64
    - name: telus_mobility_market_share 
      type: float64
    - name: videotron_market_share 
      type: float64
    - name: virgin_mobile_market_share 
      type: float64
    - name: mkt_msg_shs_cnt 
      type: int
    - name: mkt_msg_hsic_cnt 
      type: int
    - name: mkt_msg_ttv_cnt 
      type: int
    - name: mkt_msg_optik_cnt 
      type: int
    - name: mkt_msg_sing_cnt 
      type: int
    - name: mkt_msg_tos_cnt 
      type: int
    - name: mkt_msg_lwc_cnt 
      type: int
    - name: mkt_msg_wifi_cnt 
      type: int
    - name: mkt_msg_sws_cnt 
      type: int
    - name: mkt_msg_mob_cnt 
      type: int
    - name: msg_typ_EM 
      type: int
    - name: msg_typ_SO 
      type: int
    - name: msg_typ_TM 
      type: int
    - name: msg_typ_NO 
      type: int
    - name: msg_typ_SMS 
      type: int
    - name: msg_typ_ACQUISITION 
      type: int
    - name: msg_typ_CBR_FFH 
      type: int
    - name: msg_typ_HSM_West 
      type: int
    - name: msg_typ_STRATEGIC_SALE 
      type: int
    - name: msg_typ_TARGETED_CAMPAIGN 
      type: int
    - name: tot_msg 
      type: int
    - name: prod_tot_cnt 
      type: int
    - name: prod_wln_cnt 
      type: int
    - name: prod_wls_cnt 
      type: int
    - name: prod_mob_cnt 
      type: int
    - name: prod_sing_cnt 
      type: int
    - name: prod_hsic_cnt 
      type: int
    - name: prod_whsia_cnt 
      type: int
    - name: prod_ttv_cnt 
      type: int
    - name: prod_smhm_cnt 
      type: int
    - name: prod_tos_cnt 
      type: int
    - name: prod_wifiplus_cnt 
      type: int
    - name: prod_stv_cnt 
      type: int
    - name: prod_other_cnt 
      type: int
    - name: prod_deact_prod_cnt 
      type: int
    - name: prod_act_prod_cnt_r7d 
      type: int
    - name: prod_act_wln_cnt_r7d 
      type: int
    - name: prod_deact_prod_cnt_r7d 
      type: int
    - name: prod_deact_wln_cnt_r7d 
      type: int
    - name: mob_tenure_days 
      type: int
    - name: ffh_tenure 
      type: int
    - name: new_account_ind 
      type: int
    - name: wls_trip_sum_duration_days_1m 
      type: int
    - name: wls_trip_sum_duration_days_3m 
      type: int
    - name: wls_trip_sum_duration_days_6m 
      type: int
    - name: wls_trip_sum_active_roaming_days_1m 
      type: int
    - name: wls_trip_sum_active_roaming_days_3m 
      type: int
    - name: wls_trip_sum_active_roaming_days_6m 
      type: int
    - name: wls_usg_avg_data_qty_1m_roaming 
      type: float64
    - name: wls_usg_avg_sms_snd_qty_1m_roaming 
      type: float64
    - name: wls_usg_avg_sms_rcv_qty_1m_roaming 
      type: float64
    - name: wls_usg_avg_voice_qty_1m_roaming 
      type: float64
    - name: wls_usg_avg_data_qty_3m_roaming 
      type: float64
    - name: wls_usg_avg_sms_snd_qty_3m_roaming 
      type: float64
    - name: wls_usg_avg_sms_rcv_qty_3m_roaming 
      type: float64
    - name: wls_usg_avg_voice_qty_3m_roaming 
      type: float64
    - name: wls_usg_avg_data_qty_6m_roaming 
      type: float64
    - name: wls_usg_avg_sms_snd_qty_6m_roaming 
      type: float64
    - name: wls_usg_avg_sms_rcv_qty_6m_roaming 
      type: float64
    - name: wls_usg_avg_voice_qty_6m_roaming 
      type: float64
    - name: wls_usg_tot_country_code_travelled_6m_roaming 
      type: int
    - name: wls_usg_avg_data_qty_1m_domestic 
      type: float64
    - name: wls_usg_avg_sms_snd_qty_1m_domestic 
      type: float64
    - name: wls_usg_avg_sms_rcv_qty_1m_domestic 
      type: float64
    - name: wls_usg_avg_voice_qty_1m_domestic 
      type: float64
    - name: wls_usg_avg_data_qty_3m_domestic 
      type: float64
    - name: wls_usg_avg_sms_snd_qty_3m_domestic 
      type: float64
    - name: wls_usg_avg_sms_rcv_qty_3m_domestic 
      type: float64
    - name: wls_usg_avg_voice_qty_3m_domestic 
      type: float64
    - name: wls_usg_avg_data_qty_6m_domestic 
      type: float64
    - name: wls_usg_avg_sms_snd_qty_6m_domestic 
      type: float64
    - name: wls_usg_avg_sms_rcv_qty_6m_domestic 
      type: float64
    - name: wls_usg_avg_voice_qty_6m_domestic 
      type: float64
    - name: wls_usg_tot_country_code_travelled_6m_domestic 
      type: int
